import {
  competitionTrackSchema,
  researchCatalogSchema,
} from "./contracts";

export const offlineResearchCatalog = researchCatalogSchema.parse({
  schemaVersion: "research-metadata-catalog.v1",
  snapshotDate: "2026-08-12",
  liveApiCalls: 0,
  containsPersonalData: false,
  resources: [
    {
      id: "aida-life-science-terms",
      resourceKind: "dataset",
      sourcePlatform: "aida",
      title: "생명과학분야 전문용어 개체 인식 데이터셋",
      summary: "생명과학 논문의 한글·영문 제목과 초록에서 전문용어 후보와 국가과학기술표준분류 중분류를 연결한 공개 메타데이터입니다.",
      topicCodes: ["life-science-terminology", "biomedical-literature"],
      language: "ko-en",
      dataType: "json",
      sourceUrl: "https://aida.kisti.re.kr/data/95cc8200-c3b1-4c77-ab49-a311ad703ab9",
      doi: "10.23057/124",
      publishedAt: "2025-11-10",
      retrievedAt: "2026-08-12",
      accessState: "account-approval-required",
      licenseClass: "noncommercial-attribution-no-redistribution",
      redistribution: "prohibited",
      qualityWarnings: [
        "자동 태깅으로 구축되었으며 도메인 전문가의 전수 수작업 검토를 거치지 않았습니다.",
        "AIDA 페이지가 보고한 평가 F1은 69.32%이므로 정답 데이터로 간주하면 안 됩니다.",
      ],
      containsRawRecords: false,
      diagnosticUse: false,
    },
    {
      id: "aida-infectious-disease-events",
      resourceKind: "dataset",
      sourcePlatform: "aida",
      title: "해외 감염병 발생 이벤트 데이터셋",
      summary: "영문 뉴스 기사와 보고서에 언급된 감염병 발생 이벤트를 태깅한 JSON 데이터셋의 공개 메타데이터입니다.",
      topicCodes: ["infectious-disease-events", "biomedical-literature"],
      language: "en",
      dataType: "json",
      sourceUrl: "https://aida.kisti.re.kr/data/913d6e64-10fa-4682-ac98-1879a83e7c88",
      doi: "10.23057/95",
      publishedAt: "2024-10-10",
      retrievedAt: "2026-08-12",
      accessState: "account-approval-required",
      licenseClass: "research-use-review-required",
      redistribution: "unknown",
      qualityWarnings: [
        "공개 상세 페이지에서 재배포 범위를 확정할 수 없어 원문 데이터 사용 전에 별도 권리 검토가 필요합니다.",
        "뉴스 기반 사건 데이터는 환자 개인 기록이나 실시간 방역 판단 자료가 아닙니다.",
      ],
      containsRawRecords: false,
      diagnosticUse: false,
    },
    {
      id: "aida-medibio-deberta",
      resourceKind: "model",
      sourcePlatform: "aida",
      title: "MediBioDeBERTa",
      summary: "영어 의료·생물의학 문헌을 위한 DeBERTa 기반 언어모델의 공개 메타데이터입니다. 한국어 임상 진단 모델이 아닙니다.",
      topicCodes: ["biomedical-literature"],
      language: "en",
      dataType: "model-weights",
      sourceUrl: "https://aida.kisti.re.kr/model/052e095a-3573-4144-b687-52b19d66b5fc",
      doi: "10.23057/87",
      publishedAt: "2024-04-05",
      retrievedAt: "2026-08-12",
      accessState: "account-approval-required",
      licenseClass: "model-license-review-required",
      redistribution: "unknown",
      qualityWarnings: [
        "공개 페이지에 진단 성능·한국어 성능·임상 검증 근거가 제시되지 않았습니다.",
        "모델 파일을 받기 전에 라이선스, 가중치 출처, 평가 재현성을 독립적으로 검토해야 합니다.",
      ],
      containsRawRecords: false,
      diagnosticUse: false,
    },
    {
      id: "dataon-research-data-api",
      resourceKind: "catalog",
      sourcePlatform: "dataon",
      title: "DataON 연구데이터 검색·상세조회 API",
      summary: "승인된 이용자가 연구데이터 검색과 메타정보 상세조회를 수행할 수 있는 DataON OpenAPI 계약입니다.",
      topicCodes: ["life-science-terminology", "infectious-disease-events", "biomedical-literature"],
      language: "not-applicable",
      dataType: "metadata-api",
      sourceUrl: "https://dataon.gitbook.io/dataon-user-guide/sharing/openapi/api",
      retrievedAt: "2026-08-12",
      accessState: "api-and-ip-approval-required",
      licenseClass: "metadata-api-approval-required",
      redistribution: "metadata-only",
      qualityWarnings: [
        "OpenAPI 이용은 사전 승인과 등록 IP 접근통제가 필요합니다.",
        "검색 메타데이터의 노출이 원문 데이터 재배포 권한을 의미하지 않습니다.",
      ],
      containsRawRecords: false,
      diagnosticUse: false,
    },
  ],
});

export const competitionTracks = [
  competitionTrackSchema.parse({
    id: "dataon-aida-2026",
    title: "2026 DATA·AI 분석 경진대회",
    organizer: "과학기술정보통신부·국가과학기술연구회 등 / KISTI 주관",
    submissionDeadline: "2026-09-04",
    proposedEntry: "연구데이터 재사용 가능성을 출처·권리·품질 근거로 설명하는 기권 가능한 큐레이션 에이전트",
    readiness: "building",
    hardGate: "2026 접수 페이지의 최종 양식·공개 조건을 주관기관에 확인한 뒤 제출합니다.",
  }),
  competitionTrackSchema.parse({
    id: "daejeon-public-data-2026",
    title: "2026년도 공공데이터 활용 공모전",
    organizer: "공공데이터 활성화 협의체·대전권대학 산학협의체",
    submissionDeadline: "2026-08-31",
    proposedEntry: "한국연구재단 연구지원 공개데이터와 연구데이터 카탈로그를 잇는 근거 탐색 웹서비스",
    readiness: "blocked-on-eligibility",
    hardGate: "대전·세종 소재 대학의 대학(원)생 1~4인 자격을 실제 팀원이 충족해야 합니다.",
  }),
] as const;
