import type { MedicalDocumentSyntheticContractRegression } from "./evaluation.ts";

function percent(value: number) {
  return `${(value * 100).toFixed(1)}%`;
}

/** Markdown for docs/status/<date>/native-text-benchmark.md. Metrics only; no interpretation. */
export function renderNativeTextReport(report: MedicalDocumentSyntheticContractRegression, generatedAt: string) {
  const m = report.metrics;
  return [
    `# Native-text benchmark — ${report.corpusId} (${generatedAt})`,
    "",
    `Pipeline \`${report.pipelineId}\`: the document worker's PDFBox text-layer parser over the corpus generated by \`packages/korean-checkup-benchmark\`. No OCR, no model, no network. Synthetic documents only. Not a clinical, regulatory or production-accuracy claim (\`${report.evidenceLevel}\`).`,
    "",
    "| Metric | Value |",
    "|---|---|",
    `| Documents | ${m.documentCount} |`,
    `| Expected measurements | ${m.expectedMeasurementCount} |`,
    `| Returned measurements | ${m.returnedMeasurementCount} |`,
    `| Exact measurements | ${m.exactMeasurementCount} |`,
    `| Field precision | ${percent(m.fieldPrecision)} |`,
    `| Field recall | ${percent(m.fieldRecall)} |`,
    `| Field F1 | ${percent(m.fieldF1)} |`,
    `| Critical value exact | ${percent(m.criticalValueExactRate)} |`,
    `| Evidence localization (IoU ≥ 0.8) | ${percent(m.evidenceLocalizationRate)} |`,
    `| Required abstention recall | ${percent(m.requiredAbstentionRecall)} |`,
    `| Hallucinated measurements | ${m.hallucinatedMeasurementCount} (${percent(m.hallucinationRate)}) |`,
    `| Reference-range text carried verbatim | ${percent(m.referenceRangeAccuracy)} |`,
    `| Gate | ${report.gate.passed ? "PASS" : `FAIL: ${report.gate.failures.join(", ")}`} |`,
    "",
    "Thresholds: field F1 = 1, critical value exact = 1, evidence localization = 1, hallucination = 0, required abstention recall = 1, reference-range text = 1.",
    "",
  ].join("\n");
}
