import type { HandLabelledReport, MedicalDocumentSyntheticContractRegression } from "./evaluation.ts";

function percent(value: number) {
  return `${(value * 100).toFixed(1)}%`;
}

/** Markdown for docs/status/<date>/native-text-benchmark.md. Metrics only; no interpretation. */
export function renderNativeTextReport(
  report: MedicalDocumentSyntheticContractRegression,
  generatedAt: string,
  handLabelled?: HandLabelledReport,
) {
  const m = report.metrics;
  const lines = [
    `# Native-text benchmark — ${report.corpusId} (${generatedAt})`,
    "",
    `Pipeline \`${report.pipelineId}\`: the document worker's PDFBox text-layer parser over the corpus generated by \`packages/korean-checkup-benchmark\`. No OCR, no model, no network. Synthetic documents only. Not a clinical, regulatory or production-accuracy claim (\`${report.evidenceLevel}\`).`,
    "",
    "| Metric | Value |",
    "|---|---|",
    `| Documents | ${m.documentCount} |`,
    `| Expected measurements | ${m.expectedMeasurementCount} |`,
    `| Returned measurements | ${m.returnedMeasurementCount} |`,
    `| Exact measurements | ${m.exactMeasurementCount} |`,
    `| Field precision | ${percent(m.fieldPrecision)} |`,
    `| Field recall | ${percent(m.fieldRecall)} |`,
    `| Field F1 | ${percent(m.fieldF1)} |`,
    `| Critical value exact | ${percent(m.criticalValueExactRate)} |`,
    `| Evidence localization (IoU ≥ 0.8) | ${percent(m.evidenceLocalizationRate)} |`,
    `| Required abstention recall | ${percent(m.requiredAbstentionRecall)} |`,
    `| Hallucinated measurements | ${m.hallucinatedMeasurementCount} (${percent(m.hallucinationRate)}) |`,
    `| Reference-range text carried verbatim | ${percent(m.referenceRangeAccuracy)} |`,
    `| Concept code: runner and gold agree (both from the catalogue rule) | ${percent(m.conceptAccuracy)} |`,
    `| Gate | ${report.gate.passed ? "PASS" : `FAIL: ${report.gate.failures.join(", ")}`} |`,
    "",
    "Thresholds: field F1 = 1, critical value exact = 1, evidence localization = 1, hallucination = 0, required abstention recall = 1, reference-range text = 1, concept code = 1.",
    "",
  ];
  if (handLabelled) {
    lines.push(
      `## Hand-labelled layouts — ${handLabelled.corpusId}`,
      "",
      "Layout-faithful synthetic fixtures (founder decision 3): structure copies real Korean checkup sheets, content is synthetic, expectations are typed by hand — never generated. Scored separately; never folded into the metrics above.",
      "",
      "| Metric | Value |",
      "|---|---|",
      `| Expected candidates | ${handLabelled.expectedCandidates} |`,
      `| Matched candidates | ${handLabelled.matchedCandidates} |`,
      `| Expected abstentions | ${handLabelled.expectedAbstentions} |`,
      `| Matched abstentions | ${handLabelled.matchedAbstentions} |`,
      `| Hallucinated candidates | ${handLabelled.hallucinatedCandidates} |`,
      `| Candidate accuracy | ${percent(handLabelled.candidateAccuracy)} |`,
      `| Abstention accuracy | ${percent(handLabelled.abstentionAccuracy)} |`,
      `| handLabelledAccuracy | ${percent(handLabelled.handLabelledAccuracy)} |`,
      `| Regression floor | ${percent(handLabelled.floor)} |`,
      `| Gate | ${handLabelled.passed ? "PASS" : "FAIL"} |`,
      "",
    );
  }
  return lines.join("\n");
}
